### ISSUE TITLE
Integrity constraint violation

### ISSUE THREAD

**Issue by cdev38399** [yii2tech/balance#11] opened 2017-07-31 08:32 UTC
Error during transfer with message 

Integrity constraint violation – yii\db\IntegrityException
SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '8' for key 'PRIMARY'
The SQL being executed was: INSERT INTO `stockTransaction` (`id`, `date`, `extraAccountId`, `amount`, `accountId`, `data`) VALUES (8, 1501489193, 5, '5', 6, '{\"task\":\"Stock adjustment\",\"SKU\":\"SOGO\",\"name\":\"Songoku\",\"regular_price\":\"10000\",\"sale_price\":\"0\",\"voucher\":\"No\"}')

Error Info:

```
Array
(
    [0] => 23000
    [1] => 1062
    [2] => Duplicate entry '8' for key 'PRIMARY'
)
```

========================

Duplicated entry '8' is for field 'userId', not sure why it goes to 'id' field though.

========================
CONFIG

```php
'stockManager' => [
            'class' => 'yii2tech\balance\ManagerDb',
            'accountTable' => 'stockAccount',
            'transactionTable' => 'stockTransaction',
            'accountLinkAttribute' => 'accountId',
            'amountAttribute' => 'amount',
	    'extraAccountLinkAttribute' => 'extraAccountId',
            'dataAttribute' => 'data',
]
```

========================================
TRANSFER

```php
Yii::$app->stockManager->transfer(
['userId' => 0, 'type' => 'VG-' . $model->id],
['userId' => $model->id, 'type' => 'VG'],
$stock_to_adjust,
[
   task' => 'Stock adjustment',
  'SKU' => $model->SKU,
  'id' => $model->id,
  'name' => $model->name,
  'regular_price' => $model->regular_price,
  'sale_price' => $model->sale_price,
  'voucher' => $model->voucher
]);						
```

**Comment by klimov-paul** [comment] 2017-08-01 14:34
This error happens because you are passing key `id` amoung trnsaction data.

```php
Yii::$app->stockManager->transfer(
    ['userId' => 0, 'type' => 'VG-' . $model->id],
    ['userId' => $model->id, 'type' => 'VG'],
    $stock_to_adjust,
    [
        'id' => $model->id, // Write same value into 'Transaction.id' for 2 different rows
        // ...
    ]
);
```

ManagerDb always attempt to store transaction data in the column with matching name, data will be serialized only if such column does not exist.

**Comment by klimov-paul** [comment] 2017-08-01 15:15
Resolved by commit 9e3f5cfd319b7167e775be9bd730b3ba59467407

**Closed as completed by klimov-paul** 2017-08-01 15:15 UTC
Labels: bug

**Comment by cdev38399** [comment] 2017-08-01 17:35
Thanks for your quick response.
Now the record saved but the balance is not stored properly.

Example:
Yii::$app->balanceManager->increase(
[
   'userId' => \Yii::$app->user->id,
   'type' => 'PENDING TOPUP',
],
$model->amount,
);

Balance Transaction record saved properly but Balance account balance still 0 (seems like not calculated/stored).

I'm using this plugin long time ago and everything is working great, not sure why the latest is a bit problem.

Please advise.

**Comment by klimov-paul** [comment] 2017-08-02 07:43
Unable to reproduce. This use case is covered by unit test:
https://github.com/yii2tech/balance/blob/master/tests/ManagerDbTest.php#L96-L113

**Comment by cdev38399** [comment] 2017-08-03 03:58
![stock](https://user-images.githubusercontent.com/14265854/28905407-b027e79a-783a-11e7-8443-31b06874d48f.png)

**Comment by cdev38399** [comment] 2017-08-03 04:09
Opps please ignored previous message.
I forgot to set the accountBalanceAttribute.

Great plugin :)
